print('Welcome to Directed Research in AI System (I)!')
print('We hope you enjoy this exciting journey.')
print('Throughout the course, you will explore diverse domains within Artificial Intelligence.')
print('You will participate in hands-on projects and conduct independent research.')
print('By the end, you will have honed essential research skills and gained valuable experience.')
print('Stay curious, work diligently, and embrace the challenges that lie ahead.')
print('Good luck, and have a great time!')